cd
source .bashrc
config=$1
drone_num=$2
map_size_x=$3
map_size_y=$4 
map_size_z=$5
box_min_x=$6  
box_min_y=$7  
box_min_z=$8   
box_max_x=$9  
box_max_y=${10}  
box_max_z=${11}  
spawn_pos1_x=${12}
spawn_pos1_y=${13}
spawn_pos1_z=${14}
spawn_pos2_x=${15}
spawn_pos2_y=${16}
spawn_pos2_z=${17}
spawn_pos3_x=${18}
spawn_pos3_y=${19}
spawn_pos3_z=${20}
spawn_pos4_x=${21}
spawn_pos4_y=${22}
spawn_pos4_z=${23}
spawn_pos5_x=${24}
spawn_pos5_y=${25}
spawn_pos5_z=${26}
spawn_pos6_x=${27}
spawn_pos6_y=${28}
spawn_pos6_z=${29}
spawn_pos7_x=${30}
spawn_pos7_y=${31}
spawn_pos7_z=${32}
spawn_pos8_x=${33} 
spawn_pos8_y=${34}
spawn_pos8_z=${35}

roslaunch rpl_exploration exploration.launch \
    map_size_x:=$map_size_x \
    map_size_y:=$map_size_y \
    map_size_z:=$map_size_z \
    config_file:=$config \
    drone_num:=$drone_num \
    sdf_map/box_min_x:=$box_min_x \
    sdf_map/box_min_y:=$box_min_y \
    sdf_map/box_min_z:=$box_min_z \
    sdf_map/box_max_x:=$box_max_x \
    sdf_map/box_max_y:=$box_max_y \
    sdf_map/box_max_z:=$box_max_z \
    spawn_pos1_x:=$spawn_pos1_x \
    spawn_pos1_y:=$spawn_pos1_y \
    spawn_pos1_z:=$spawn_pos1_z \
    spawn_pos2_x:=$spawn_pos2_x \
    spawn_pos2_y:=$spawn_pos2_y \
    spawn_pos2_z:=$spawn_pos2_z \
    spawn_pos3_x:=$spawn_pos3_x \
    spawn_pos3_y:=$spawn_pos3_y \
    spawn_pos3_z:=$spawn_pos3_z \
    spawn_pos4_x:=$spawn_pos4_x \
    spawn_pos4_y:=$spawn_pos4_y \
    spawn_pos4_z:=$spawn_pos4_z \
    spawn_pos5_x:=$spawn_pos5_x \
    spawn_pos5_y:=$spawn_pos5_y \
    spawn_pos5_z:=$spawn_pos5_z \
    spawn_pos6_x:=$spawn_pos6_x \
    spawn_pos6_y:=$spawn_pos6_y \
    spawn_pos6_z:=$spawn_pos6_z \
    spawn_pos7_x:=$spawn_pos7_x \
    spawn_pos7_y:=$spawn_pos7_y \
    spawn_pos7_z:=$spawn_pos7_z \
    spawn_pos8_x:=$spawn_pos8_x \
    spawn_pos8_y:=$spawn_pos8_y \
    spawn_pos8_z:=$spawn_pos8_z \
